* the talk about Mehrieh
** my questions
*** TODO Mehrieh
**** She cares about Mehrieh either she is lying to me or she is lying to herself as well
     she said if it wasn't you, i would have done something to the extend of breaking off or something
     it's clear that she cares about it, I'm not gonna argue about this point
**** how come she has not offered any thing to me like giving it away afterwards or something to that extend
**** What is the normal number from her perspective
**** what is the normal number from her father's perspective
**** how many time has she had the very same experience of being proposed of 
     her idiot brother boasted about putting potential proposals to the rest,
     now she says something which might corroborate the same narrative.
     
     do i even want to know that?
     i can tell her about few relationships that i had which lead to no romantic involvement
**** base on last night estimation i can provide 19.2 gold coins from my entire savings  
**** i talked about lots of other things that she could not have easily gained but they fall on deaf ears it seems
**** [#A] Why her father's view should change if i put forward my position on Mehrieh :logical:
**** Why would her father think differently about me after talking about Mehrieh
**** [#A] why offering all my savings are not enough ?
*** TODO regrets 
**** [#A] I feel dumb for the being in the situation like this. :insecurity:emotional:
     i tried my best in the time limit that i had.
**** [#A] Did i abuse her feelings                     :insecurity:emotional:
     at the very least i did not intent to
*** TODO Proposal
**** If she knew the number would have said yes to my proposal?
**** [#A] If she know my position would she had said yes to my proposal? :emotional:insecurity:logical:
*** TODO [#A] personality and conflict resolution
**** [#A] I felt a hostility in the beginning of the conversation   :logical:
     an attack posture, then a sudden change into defenseless thing, was it an
     strategy to attack and when i hold my ground turn back.

     i am almost certain this defenseless happened after she was saying if you
     know me by then ... and i asked her please do not talk to me like that.
**** [#A] is she actually independent? is she her own person?       :logical:
**** [#A] i point blank asked her for a number, she said i don't care
     then i said something and now she is offended by my audacity to put a number forward, i will not let this one slide
**** i feel powerless about controlling her emotions or better say emotional management :emotional:
**** it is very important how the conversation will pan out this time :logical:
     does she attack and retreat in the same manner as saturday
     is she going to be a pacifist?
     is she going to attack again?
     is she going to cry to get out of it?
**** [#A] is the reason for avoid conflicts is her lack of ability to control the arguments
**** [#A] where was the conversation going if i didn't interrupt it?
    she was talking to me about if you are thinking this way you don't know me
    and it was going to be out of control then i said please don't talk to me
    like that and she broke into tears i guess.
**** [#A] I need to actually see how she argues 
**** was it a trap to get me to say a number then use it as a hammer on me
     since she wasn't aware of the topic, so it's very unlikely that it was a
     plan. on the other hand she 
**** [#A] There are loads of little things that are now quite important, Was i a dummy to not care about them :insecurity:logical:
     - like who call who and when
     - who says hi in the begining
     - For instance right now she knows i am not happy and a bit hurt ( a lot
       actually ) but so far she has not sent me a message. at the very least i
       expected a hello today.
**** How close is the relationship between her and her parents
     one thing that caught my attention, was that she mentioned that why i am
     supposed to break my father's heart, what that even mean.
*** TODO trust 
**** [#A] Can i trust her not to blindly use my own words out of context to attack me
     definitely the use of my own words and saying how dare i put
**** [#A] does sharing my emotions even count
**** [#A] How much the talk we had Saturday nigh was honest and how much of it was politics 
**** did i make a mistake in how the relationship progressed?     :emotional:
     maybe yes
**** where did i make this relationship progression mistake       :emotional:
     - did i propose too soon
     - did i open myself too fast
     - 
**** What are the other things that she care about but you don't know
**** [#A] she said how could you logically think about it.
     how come she did not see my logic in almost every action i did. now she is
     accusing me of being logic and hurt in the matter. Then she can easily talk
     about "no i would not want a penny even if i was mad at you". This is
     heartless at the very least.
**** [#B] how-come she can easily talk about when we become separated
     when i talked about it, i became emotional.
**** [#A] What are her red-lines                                    :logical:
*** TODO actions
**** [#A] I definitely Don't want her to be my spokesmen when it comes to this
     She proved to be incapable of correctly conveying my message, and at best it
     would be misunderstanding or at worst it would be a disaster.

     I need to take charge here, maybe a show of will or force is required.
     I am worried about the brother but if he jumps in i will put him down fast.
**** I feel like i am in the wrong here, things should not have escalated this far
     well i feel quite shitty about the things that happened, i feel i need to
     change a few things, like the level of intimacy we have right now. 

     in the original note i kept repeating "i should not have kissed her"
     fuck this country and it's culture. 
**** [#A] Should i reduce 14 to a symbolic 1 or something else like a Haj of whatever :action:logical:
     It still burns to think about the way
     she said How could you reduce it to a number
** questions to ask
*** do explain that this conversation is not gonna be easy but i expect her to hold her own.
*** ask about yesterday, what happened
*** do you remember the things that i said on Friday?               :Mehrieh:
*** first stablish that she cares about Mehrieh                     :Mehrieh:
*** second ask point blank about normal number from her perspective and his father's :Mehrieh:

    تعداد معقول چندتاست

    150 - 200

*** what is her father view and how it's going to change            :Mehrieh:

*** what did she mean by breaking his father's heart                :Mehrieh:
