* [2022-05-18 Wed]
today i had a very strage conversation with fatemeh, i was quite disapointed of her for ignoring my call.

how was my trip?
how was my working day?
why did i work through the night?

the audacity of her, I DID NOT ASK HER WHY SHE WAS BUSY DURING THE WEEK!
she did not care about any of them.


i suspect she asked about the trip to change the course of the conversation because it was going very bad.


you might be happy with the way it ended but i'm not.

I am too sensitive i guess according to her.


i really feel angry at the moment. i feel manupulated.

she keep saying this is the way i am. well this is the way I AM.
i don't think i can maitain the relation ship any more.
it's not a relationship.
what is it?
a friendship?
I don't have friends like her.
I dont feel that good about her any more!


the conversation we had was not the definition of quality of time.
it was basically a shit show.
maybe i'm too demanding.

i think i need to talk to a shrink about it. because i feel there is something fundementally wrong here with me.

why do i feel there is something fundementally worng?
because i'm talking to myself about the conversation that needed to end quite soon.

when i call

why the hell do i feel this sad?
i cant tell exactly why i'm this sad?
is it because i feel i'm loosing something?
is it because i feel that i'm being ignored?
why being ignored is this bad for me?

i need to investigate why i feel this way about being ignored?
what is it that makes me feel like this?
what expectation i'm having which cause this level of disapointment?
i'm disapointed by the fact that i expected to be more valueable,
why do i feel disvalued?
why should she has this effect on me?
do i love her? i certainly believe it's not love!


what is value?
how valueable i am?
the things that i am proud of.
 - the level of professional situation that i have.
 - the level of accomplishment that i have
   what are my accomplishments?
   what i am gratefull for?



 what is the thing that i'm discussing with fatemeh that is not quite right?
 she mentioned that i'm talking ironically.


 what i need in this relationship that would benefit me?
 what would i learn from her?
 is she worth learning any thing from?



I started this conversation with fatemeh, knowing full fell it's not gonna end well. i did it any way.
my tone is consered to be accusatory, which i need to consider. i highly suspect what she said to be bullshit and she might be gaslighting me.
however the fact that she can say my tone was considered accusatory is concerning.


i'm mentally exhausted by this conversation.


it's very strage and insulting that she expects me to ask how her day was when
she has never actually shown interest in what is happening in my work place, she
says i'm ignoring things you are throwing my way sarcastically.



i have a hard time placing her in a place suitable to her action and level of
communication that is not taxing for my psychie. for this one i need to change
the way i see her and drastically reduce the mental burden for myself.

I need to revaluate the level of relationship that i'm having with her.








what i wanna do regarding fatemeh
   - i have a 
   - first stop caring about what she wants
   - stop trying to maintain the communication, if you happen to send something 
   - 
   

* [2022-05-19 Thu]
stupidity has no bounds.
i can't tell if she has no understanding for the type of things she dose or



i feel very sad at the moment. what y do i feel sad is not quite clear.

i feel

* [2022-05-24 Tue]
today i had a very strage and probably relationship ending talk with fatemeh.


i hate that she is emotionless and do not care at all about dealing with people.

i feel very sad at the moment.
i feel like i have lost something.
i feel like i have been rudely put aside.


why i am keeping the communication with her?


actually i'm thinking just too much about what she is and how she acts.

i'm not even sexually fascinated by her.
i remember the very fist time that i have seen her, the very fist thing that jump to me was her face.

i feel like an idiot. i should have not text her afterwards, definately i should have not called her again.

i'm thinking about the situation in a stupid way.
she definately is not suitable for any type of friendship let alone relationship.

* [2022-05-25 Wed] 
I am writing this since i am pretty sure since you feel i have wounded your
pride, you are not gonna contact me again. I am not in the habit of removing the
contacts, or deleting history. but in this case i have since i realized you are
not worthy of any effort to maintain any type of relationship. I'm writing this
since i know i'm not gonna tell you any of them. The question remains why i'm writing this.

I'm doing it because i don't want you to occupy any part of my brain, and you
are not going to live in my mind rent free even for few days any more.

the level of misunderstanding and the level of stupidity or carelessness in your
part has cause this frustration and what had followed. I do not regret what i
have told you so far and i regret tolerating this stupid dynamic up to this point.

I have not been in Love with you and i did not wanted to pursue marriage. I
wanted to relive the past experience that i had. After a breakup with such high
intensity, the nostalgia brought me back to you. now i understand why it's a
hard fast rule to never go back in time. because of the past i have given you
the position you did not deserve to have. Based on the way you carry yourself i
would say you lack basic knowledge of how relationships work.

Actually i expected to write more than this but it seems my mind has ran it's
course. It's quite over now. Last time it took me almost two month but now, you
are going to go out in almost two days now. Enjoy your life.

* talk with nima
i feel humilated right now. why do i feel like this? the reason is i feel attacked

why did he wanted to micro manage me?
dose he has a purpose in doing so? i thinks he wants to show me who is the boss!

i am angry because he do not pay an attenetion to my well being?
am i an idiot?
yeah.
why the fuck should i even bother or put myself under presure to fix things that are not important.
I have to take care of my health and well being all by myself. it's stupid to think nima cares about either of them.


what i want in the company.
- proper autonamy to manage my team. I do not tolerate micro management.
- proper specification of my rule in the company. Am i the CTO or the team leader.
