* decentralized communication
** activityPub
** fediverse
** JSON-LD
** DID
   decentralized identifier
** file storage
*** IPFS
*** CEPH
*** SIA
*** GlusterFS
*** freenet
** mastodon
   social network
* email/calander
  https://www.youtube.com/watch?v=sP5le4gSryM
** proton mail
   https://gist.github.com/A6GibKm/238b754a4a90051f60906b9efa3e8000
** net-c
** zoho mail
* browser
** blink
   google engine
** firefox
* search engine
** duckduckgo
** Qwant
* meta search engine 
  there is a problem within search engines, they have very huge power to sensor
  the things they want to because most people only find the things they are
  interested in from search engines. Now if a search engine decides to ban a
  contents they have the ability to do so. We need a democratized meta search
  engine which gives the ability to find the contents that people are interested
  in with out any prejudice. Meta search engine to provide more information over
  the traditional search engines.
* digital currencies
** wallet
   [[https://www.coinomi.com/en/downloads/ ][coinomi]]
