* Reach out to new people
  having old friends where you know thier history and can laugh at
  inside jokes is a good thing, however the problem is no new idea is
  generated in these circles and you endup with same ideas and
  perspective ove and over again.

  new people on the other hand give you fresh prespective/ new ideas
  in life, which will expand your horizen.

 - introduce yourself to one new person a week.
* Do not be averse to change
  do not resist changes, be open to new concepts and carious about the world
* be open to taking risk
  no risk and save -> boring and mundane
  consider if you will be unhappy in long run if you dont take that chanse
* you dont deserve success based on your credential
  you dont deserve something just because you are smart,
  you get result basd on
  - hardwork
  - stratigic thinking
  - luck
* value your time  
  spend in on few project that make every thing great no what ever
  seems interesting at time. spending time on one thing mean you are
  possibly missing out on something else.
* Commit to a decision
  having too many option makes it hard to decide, do some research
  before makeing a decision but stick to it afterwards.
* believe in yourself
  you are your own worst critic, do not second guess your work,
  prefrectinisim will hinder your progressm. Getting started beat
  waiting for something to happen every time.
