* testing methods
** insult you to see how you react 
** playing hard to get to see if you obsessively start pursing them 
** being cold to see how you handle up and down
** jealousy
** betraying your value
* green flags
** no game
** supportive 
   does she support my dreams or not 
   - diet or something like that
   be a big cheer leader
** interested 
   asking a lot of questions about you

   she has her own interest but she follows 
** communication skills 
   accurately express their feelings, so you know if something is wrong

   if she is in a bad mood she talks about it

   she should be communicate with you about her problems
** she has friends
   they have relationship outside of you.
   if she has burned a lots of bridges it is a red flag 
** she is interdependent 
   independent 
   she has things that do not involve you. she has a life outside of you.
** She is kind
   how she treats people she doesn't know
   how she treats people she knows

   she does not gossip about people.
** glass half-full
   she sees the positive in most situation.
   makes the best out of situation
** has some kind of goal or ambition
   ambitious girl is not the lazy girl
   no dream, no ambition is a very bad sign.
* 6 types to avoid
  [[https://www.youtube.com/watch?v=G3jPH1iR4rs][6 Types of Women To Avoid.. NEVER Date These Girls!]]
** insecure girl
   she lets her insecurity runs her entire life
   she hates herself 
   she is jealous when she has no reason to
** the materialistic girl
   the gold digger
   
   she wants you to provide all the materialistic needs
   and she is not contributing 
   the moment you stop spending she is going to be out of the door
** the girl with no girlfriend 
   it is important to have friends 
   
   when someone can not maintain friendships, there is some issue here.
** the lazy girl
   she has no hobbies, she dose't know what she wants to do.

   she spends lots of time on social media 
** the attention addict
   instagram all the time, posting photos to grab attention

   she is the cheater type.
** rebound seeker
   she just came out of relationship and she wants to be serious with you.
* 9 biggest turnons for woman
** Confidence
   be secure with yourself and what you bring to the table 
** chivalry( not sure about it) 
** scene of humor 
** be kind 
** pay complement
** being on time
** extra effort for your health/grooming
   look your best
** keeping your word
** be vulnerably( not sure about it either ) 
* if she is intimidated by you
** she avoids eye contact in a shy manner
** her body is turned away from you
** loud vs quiet 
   they speak in a quiet voice
** fidgeting
   fidget with her hair or body
** pause before and after she speak
** shrink the amount of space she occupy 
* having a game (social skill)
huge part of having a game is having a personality that people will remember you by
** speak calmly 
** capable of making other people laugh
   saying what you want to say out weight getting a laughter but laugh helps
   defuse serious tension
** speak your mind
** do put with too much( don't be a doormat)
   do not let people to insult you too much
   
   standing up for yourself
   do not over react over small things 
** do not be timid
   ask and you shall be receive 
* TODO [[https://www.youtube.com/watch?v=SJ1EsWONbuY][how to 10X your focus]]
  - State "TODO"       from              [2021-03-26 Fri 04:37]
  - 
* good habits
** grooming habit 
*** skin care routine
*** white teeth 
** working out
** wake up early
** introspective activities
   - reading
   - yoga
   - painting
   - what ever that has nothing to do with screens
** hobbies
** dressing well 
** plan your day
* [[https://www.youtube.com/watch?v=cpHNwgM1_oE][6 type of charisma that women find irresitable]]
** cool type
** the giver
   laugh easily at jokes
** goof ball
** attention grabber 
** story teller
