* sid information
  sid is stored in page, it dose get set in a script tag however i have no idea where it is comming from
  - window.utag_data
  - booking.env.b_sid

* urls
** istanbul fri,Dec28- Mon Dec31 2 adults 0 children
   - https://www.booking.com/searchresults.en-us.html?label=gen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID&sid=0f1b27e2213e03597d627f2373a9316d&sb=1&src=index&src_elem=sb&error_url=https%3A%2F%2Fwww.booking.com%2Findex.html%3Flabel%3Dgen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID%3Bsid%3D0f1b27e2213e03597d627f2373a9316d%3Bsb_price_type%3Dtotal%26%3B&ss=Istanbul&is_ski_area=0&ssne=Istanbul&ssne_untouched=Istanbul&dest_id=-755070&dest_type=city&checkin_month=12&checkin_monthday=28&checkin_year=2018&checkout_month=12&checkout_monthday=31&checkout_year=2018&no_rooms=1&group_adults=2&group_children=0&b_h4u_keep_filters=&from_sf=1
   - https://www.booking.com/searchresults.html?label=gen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID;sid=95f6bfe9d4fbc69be4318916750090f0;ac_click_type=b&ac_position=0&checkin_month=12&checkin_monthday=28&checkin_year=2018&checkout_month=12&checkout_monthday=31&checkout_year=2018&class_interval=1&dest_id=-755070&dest_type=city&dtdisc=0&from_sf=1&group_adults=2&group_children=0&iata=IST&inac=0&index_postcard=0&label_click=undef&no_rooms=1&offset=0&postcard=0&raw_dest_type=city&room1=A%2CA&sb_price_type=total&search_selected=1&shw_aparth=1&slp_r_match=0&src=index&src_elem=sb&ss=Istanbul%2C%20Marmara%20Region%2C%20Turkey&ss_all=0&ss_raw=Istanbul%2C&ssb=empty&sshis=0&
   - https://www.booking.com/searchresults.en-us.html?label=gen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID&sid=896e917ee6ad11a0fa8ff1910074fe12&sb=1&src=index&src_elem=sb&error_url=https%3A%2F%2Fwww.booking.com%2Findex.html%3Flabel%3Dgen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID%3Bsid%3D896e917ee6ad11a0fa8ff1910074fe12%3Bsb_price_type%3Dtotal%26%3B&ss=Istanbul%2C+Marmara+Region%2C+Turkey&is_ski_area=&checkin_month=12&checkin_monthday=28&checkin_year=2018&checkout_month=12&checkout_monthday=31&checkout_year=2018&no_rooms=1&group_adults=2&group_children=0&b_h4u_keep_filters=&from_sf=1&ss_raw=ista&ac_position=0&ac_langcode=en&ac_click_type=b&dest_id=-755070&dest_type=city&iata=IST&place_id_lat=41.008171&place_id_lon=28.974446&search_pageview_id=f405398eb0c60060&search_selected=true&search_pageview_id=f405398eb0c60060&ac_suggestion_list_length=5&ac_suggestion_theme_list_length=0
   - https://www.booking.com/searchresults.en-us.html?label=gen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID&sid=2bf8ccc064c6ecdb89acd4ede6d39ad6&sb=1&src=index&src_elem=sb&error_url=https%3A%2F%2Fwww.booking.com%2Findex.html%3Flabel%3Dgen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID%3Bsid%3D2bf8ccc064c6ecdb89acd4ede6d39ad6%3Bsb_price_type%3Dtotal%26%3B&ss=Istanbul%2C+Marmara+Region%2C+Turkey&is_ski_area=&checkin_month=12&checkin_monthday=28&checkin_year=2018&checkout_month=12&checkout_monthday=31&checkout_year=2018&no_rooms=1&group_adults=2&group_children=0&b_h4u_keep_filters=&from_sf=1&ss_raw=is&ac_position=0&ac_langcode=en&ac_click_type=b&dest_id=-755070&dest_type=city&iata=IST&place_id_lat=41.008171&place_id_lon=28.974446&search_pageview_id=c8de39a017a002ef&search_selected=true&search_pageview_id=c8de39a017a002ef&ac_suggestion_list_length=5&ac_suggestion_theme_list_length=0
   - https://www.booking.com/searchresults.en-us.html?label=gen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID&sid=6613cfb4376f102c1df2bcc77a5a0386&sb=1&src=index&src_elem=sb&error_url=https%3A%2F%2Fwww.booking.com%2Findex.html%3Flabel%3Dgen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID%3Bsid%3D6613cfb4376f102c1df2bcc77a5a0386%3Bsb_price_type%3Dtotal%26%3B&ss=Istanbul%2C+Marmara+Region%2C+Turkey&is_ski_area=&checkin_month=12&checkin_monthday=28&checkin_year=2018&checkout_month=12&checkout_monthday=31&checkout_year=2018&no_rooms=1&group_adults=2&group_children=0&b_h4u_keep_filters=&from_sf=1&ss_raw=ist&ac_position=0&ac_langcode=en&ac_click_type=b&dest_id=-755070&dest_type=city&iata=IST&place_id_lat=41.008171&place_id_lon=28.974446&search_pageview_id=de8c39bf0677006e&search_selected=true&search_pageview_id=de8c39bf0677006e&ac_suggestion_list_length=5&ac_suggestion_theme_list_length=0
   - https://www.booking.com/searchresults.html?label=gen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID;sid=dd9d81f85ce0c1a0ca562eae783b18f5;ac_click_type=b&ac_position=0&checkin_month=12&checkin_monthday=28&checkin_year=2018&checkout_month=12&checkout_monthday=31&checkout_year=2018&class_interval=1&dest_id=-755070&dest_type=city&dtdisc=0&from_sf=1&group_adults=2&group_children=0&iata=IST&inac=0&index_postcard=0&label_click=undef&no_rooms=1&offset=0&postcard=0&raw_dest_type=city&room1=A%2CA&sb_price_type=total&search_selected=1&shw_aparth=1&slp_r_match=0&src=index&src_elem=sb&ss=Istanbul%2C%20Marmara%20Region%2C%20Turkey&ss_all=0&ss_raw=ista&ssb=empty&sshis=0&
   - https://www.booking.com/searchresults.html?label=gen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID;sid=69abf7331718b2cb2332a2c16e12aad3;ac_click_type=b&ac_position=0&checkin_month=12&checkin_monthday=28&checkin_year=2018&checkout_month=12&checkout_monthday=31&checkout_year=2018&class_interval=1&dest_id=-755070&dest_type=city&dtdisc=0&from_sf=1&group_adults=2&group_children=0&iata=IST&inac=0&index_postcard=0&label_click=undef&no_rooms=1&offset=0&postcard=0&raw_dest_type=city&room1=A%2CA&sb_price_type=total&search_selected=1&shw_aparth=1&slp_r_match=0&src=index&src_elem=sb&ss=Istanbul%2C%20Marmara%20Region%2C%20Turkey&ss_all=0&ss_raw=I&ssb=empty&sshis=0&
   - https://www.booking.com/searchresults.en-us.html?label=gen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID&sid=6ac57063c26e09fe676963980b8b95e8&sb=1&src=index&src_elem=sb&error_url=https%3A%2F%2Fwww.booking.com%2Findex.html%3Flabel%3Dgen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID%3Bsid%3D6ac57063c26e09fe676963980b8b95e8%3Bsb_price_type%3Dtotal%26%3B&ss=Istanbul%2C+Marmara+Region%2C+Turkey&is_ski_area=&checkin_month=12&checkin_monthday=28&checkin_year=2018&checkout_month=12&checkout_monthday=31&checkout_year=2018&no_rooms=1&group_adults=2&group_children=0&b_h4u_keep_filters=&from_sf=1&ss_raw=ist&ac_position=0&ac_langcode=en&ac_click_type=b&dest_id=-755070&dest_type=city&iata=IST&place_id_lat=41.008171&place_id_lon=28.974446&search_pageview_id=f5153a1def4f0140&search_selected=true&search_pageview_id=f5153a1def4f0140&ac_suggestion_list_length=5&ac_suggestion_theme_list_length=0
   - https://www.booking.com/searchresults.html?label=gen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID;sid=bfa7afb453e471a00890cb03b88596d3;ac_click_type=b&ac_position=0&checkin_month=12&checkin_monthday=28&checkin_year=2018&checkout_month=12&checkout_monthday=31&checkout_year=2018&class_interval=1&dest_id=-755070&dest_type=city&dtdisc=0&from_sf=1&group_adults=2&group_children=0&iata=IST&inac=0&index_postcard=0&label_click=undef&no_rooms=1&offset=0&postcard=0&raw_dest_type=city&room1=A%2CA&sb_price_type=total&search_selected=1&shw_aparth=1&slp_r_match=0&src=index&src_elem=sb&ss=Istanbul%2C%20Marmara%20Region%2C%20Turkey&ss_all=0&ss_raw=is&ssb=empty&sshis=0&
** istanbul fri,Dec28- Mon Dec31 2 adults 0 children lowest price first
   - https://www.booking.com/searchresults.en-us.html?label=gen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID&sid=e21ae0d81de12f771b98f6092c7b8573&tmpl=searchresults&ac_click_type=b&ac_position=0&checkin_month=12&checkin_monthday=28&checkin_year=2018&checkout_month=12&checkout_monthday=31&checkout_year=2018&class_interval=1&dest_id=-755070&dest_type=city&dtdisc=0&from_sf=1&group_adults=2&group_children=0&iata=IST&inac=0&index_postcard=0&label_click=undef&no_rooms=1&postcard=0&raw_dest_type=city&room1=A%2CA&sb_price_type=total&search_selected=1&shw_aparth=1&slp_r_match=0&src_elem=sb&ss=Istanbul%2C%20Marmara%20Region%2C%20Turkey&ss_all=0&ss_raw=i&ssb=empty&sshis=0&order=price
   - https://www.booking.com/searchresults.html?label=gen173nr-1FCAEoggI46AdIM1gEaKcCiAEBmAExuAEXyAEM2AEB6AEB-AECiAIBqAID&sid=e095a03ee8a794d4e971021143ef4976&ac_click_type=b&ac_position=0&checkin_month=12&checkin_monthday=28&checkin_year=2018&checkout_month=12&checkout_monthday=31&checkout_year=2018&class_interval=1&dest_id=-755070&dest_type=city&from_sf=1&group_adults=2&group_children=0&iata=IST&label_click=undef&no_rooms=1&raw_dest_type=city&room1=A%2CA&sb_price_type=total&search_selected=1&shw_aparth=1&slp_r_match=0&src_elem=sb&srpvid=99093aa5461100ca&ss=Istanbul%2C%20Marmara%20Region%2C%20Turkey&ss_raw=i&ssb=empty&order=price
* using curl
  using curl we can download the content but it is brotli compressed due to -H 'Accept-Encoding: gzip, deflate, br'
  using apt install brotli we can decompress
  cat html2|brotli -d|less

  curl 'https://www.booking.com/searchresults.en-us.html?label=gen173nr-1FCAEoggI46AdIM1gEaG-IAQGYATG4ARfIAQzYAQHoAQH4AQKIAgGoAgM&sid=0f1b27e2213e03597d627f2373a9316d&sb=1&src=index&src_elem=sb&error_url=https%3A%2F%2Fwww.booking.com%2Findex.html%3Flabel%3Dgen173nr-1FCAEoggI46AdIM1gEaG-IAQGYATG4ARfIAQzYAQHoAQH4AQKIAgGoAgM%3Bsid%3D0f1b27e2213e03597d627f2373a9316d%3Bsb_price_type%3Dtotal%26%3B&ss=Istanbul%2C+Marmara+Region%2C+Turkey&is_ski_area=&checkin_month=1&checkin_monthday=29&checkin_year=2019&checkout_month=2&checkout_monthday=1&checkout_year=2019&no_rooms=1&group_adults=2&group_children=0&b_h4u_keep_filters=&from_sf=1&ss_raw=is&ac_position=0&ac_langcode=en&ac_click_type=b&dest_id=-755070&dest_type=city&iata=IST&place_id_lat=41.008171&place_id_lon=28.974446&search_pageview_id=45d886461e85036d&search_selected=true&search_pageview_id=45d886461e85036d&ac_suggestion_list_length=5&ac_suggestion_theme_list_length=0' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9' -H 'Cookie: cors_js=1; _gcl_au=1.1.38458775.1544902406; _ga=GA1.2.372227484.1544902407; zz_cook_tms_seg1=1; zz_cook_tms_ed=1; cto_lwid=739d9ce2-7cd0-47c1-acc4-26e33f3075e1; _tq_id.TV-451827-1.3b4c=e77a107d2689d895.1544904869.0.1546367440..; header_signin_prompt=1; _gid=GA1.2.1087340901.1548788751; BJS=-; zz_cook_tms_seg3=5; has_preloaded=1; zz_cook_tms_hlist=3538902; _fbp=fb.1.1548792711741.2018846195; cws=true; utag_main=v_id:0167b35bfea500780d2b4e15f5b003073001806b00bd0$_sn:11$_ss:0$_st:1548797646611$4split:1$4split2:2$ses_id:1548795836720%3Bexp-session$_pn:2%3Bexp-session; _tq_id.TV-634572-1.3b4c=7141920206274933.1548795848.0.1548795848..; bkng=11UmFuZG9tSVYkc2RlIyh9YfDNyGw8J7nzPnUG3Pr%2Bfv4Q1Al3ATVwkzjZPY2r7qIcyBvUqsm6x6trvZkCy3iK%2BXD6catEeMBhsn9LDYj%2F4oxesWyMzxZkbp91yo3fqLjdnXMuyz1y1q118QZiZAW48BCrCmB%2FHN3Ebzh3Y3s3tGP2gwce2KJnz4%2F%2BlQrfFSAh5yemkUJNeFEtYKeunwIxvw%3D%3D; lastSeen=0' --compressed -H "Accept-Encoding: gzip"  -o html2
* using apachee http client
 somehow apachee http client is detected by booking( maybe sending something to them )
** https://www.booking.com/hotel/tr/polatdemir.html
<!DOCTYPE html>
<!--
You know you could be getting paid to poke around in our code?
We're hiring designers and developers to work in Amsterdam:
http://www.workingatbooking.com/
-->
<!-- wdot-802 -->
<html lang="en-us" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# booking_com: http://ogp.me/ns/fb/booking_com#" xmlns:og="http://opengraphprotocol.org/schema/" class="noJS b_bot b_bot supports_fontface supports_hyphens " >
<head profile="http://a9.com/-/spec/opensearch/1.1/">
<meta name="referrer" content="origin">
<meta http-equiv="content-type" content="text/html; charset=utf-8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
** https://www.booking.com/searchresults.en-us.html?label=gen173nr-1FCAEoggI46AdIM1gEaG-IAQGYATG4ARfIAQzYAQHoAQH4AQKIAgGoAgM&sid=0f1b27e2213e03597d627f2373a9316d&sb=1&src=index&src_elem=sb&error_url=https%3A%2F%2Fwww.booking.com%2Findex.html%3Flabel%3Dgen173nr-1FCAEoggI46AdIM1gEaG-IAQGYATG4ARfIAQzYAQHoAQH4AQKIAgGoAgM%3Bsid%3D0f1b27e2213e03597d627f2373a9316d%3Bsb_price_type%3Dtotal%26%3B&ss=Istanbul%2C+Marmara+Region%2C+Turkey&is_ski_area=&checkin_month=1&checkin_monthday=29&checkin_year=2019&checkout_month=2&checkout_monthday=1&checkout_year=2019&no_rooms=1&group_adults=2&group_children=0&b_h4u_keep_filters=&from_sf=1&ss_raw=is&ac_position=0&ac_langcode=en&ac_click_type=b&dest_id=-755070&dest_type=city&iata=IST&place_id_lat=41.008171&place_id_lon=28.974446&search_pageview_id=45d886461e85036d&search_selected=true&search_pageview_id=45d886461e85036d&ac_suggestion_list_length=5&ac_suggestion_theme_list_length=0
<html>
<head><title>403 Access Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Access Forbidden</h1></center>
<hr>
<p>
You have been detected as a robot accessing the site in violation
of our <a href="https://www.booking.com/content/terms.html">terms of service</a>.
</p>
<p>
We will block you unless:
</p>
<ol>
<li>
You identify yourself in your user agent string, and include the word 'robot' and an
email address where we may contact you ('robot &lt;your.email@domain.com&gt;').
The email address <b>may</b> be anonymised but mails to it <b>must</b> be answered.
</li>
<li>
You fetch from us in an even and consistent manner that does not produce load
spikes in our systems and impair our service to our customers.
</li>
</ol>
<p><b>Warning:</b> continued violation of TOS is a criminal offense in many jurisdictions.
<p>
Please contact us at <a href="mailto:robotcontact@booking.com">robotcontact@booking.com</a> in case you think this is an
error or if you have any questions.
</p>
</body>
</html>
** test
curl 'https://www.booking.com/navigation_times?sid=0b10e57d88a351c574e006e2a9d5a029&pid=f87d315a89d900a3&nts=1,0,1553670069461,1553670070226,1553670070226,0,0,1553670069464,1553670069466,1553670069466,1553670069466,1553670069811,1553670069636,1553670069811,1553670070220,1553670071977,1553670070246,1553670072288,1553670072290,1553670072326,1553670078752,1553670078753,1553670078758,0&first=0&cdn=bs&dc=1&bo=3&lang=en-us&ref_action=searchresults&aid=304142&stype=2&route=&ua=302&ch=m&lt=&css_load=0&wn=0' -H 'Origin: https://www.booking.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'X-Booking-CSRF: 9lebXAAAAAA=alaHWyXahqK5hF1wI6qvrg_W938jQBcG12Dg-Sx9HhfSZ2hBWWRrtKDAcceWfyiAaqKW9pqEVuWBtqNxxP7qyUIsY9XlzyDB-QjUzIRNnrqShIgJo5SpjCPu-up1KS68V4Ni6pxjAoRVAiNYvpP4urdKMVkzYuYOLC24WYcSSNS50c6UNgncB3Wa9CDQaiiva5VCDVbEciNsKUHl' -H 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Mobile Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept-Language: en-US,en;q=0.9' -H 'Accept: */*' -H 'Referer: https://www.booking.com/searchresults.html?label=gen173nr-1FCAEoggI46AdIM1gEaDuIAQGYATG4ARjIAQzYAQHoAQH4AQKIAgGoAgS4Aue77OQFwAIB&sid=0b10e57d88a351c574e006e2a9d5a029&ac_click_type=b&ac_position=0&checkin_month=3&checkin_monthday=29&checkin_year=2019&checkout_month=4&checkout_monthday=2&checkout_year=2019&class_interval=1&dest_id=-755070&dest_type=city&dtdisc=0&from_sf=1&group_adults=2&group_children=0&iata=IST&inac=0&index_postcard=0&label_click=undef&no_rooms=1&offset=0&postcard=0&raw_dest_type=city&room1=A%2CA&sb_price_type=total&search_selected=1&shw_aparth=1&slp_r_match=0&src=index&src_elem=sb&ss=Istanbul%2C%20Marmara%20Region%2C%20Turkey&ss_all=0&ss_raw=istanbul&ssb=empty&sshis=0' -H 'Cookie: cors_js=1; cws=true; header_signin_prompt=1; vpmss=1; BJS=-; _gcl_au=1.1.1826073607.1553669635; zz_cook_tms_seg1=2; zz_cook_tms_ed=1; zz_cook_tms_seg3=5; cto_lwid=c96046f0-776a-4649-a74f-8d0b26825611; has_preloaded=1; lastSeen=1553669820626; _ga=GA1.2.1450599918.1553669822; _gid=GA1.2.572227747.1553669822; _tq_id.TV-274536-1.3b4c=8744f863aa0d5f5d.1553669642.0.1553669824..; _gat=1; bkng=11UmFuZG9tSVYkc2RlIyh9Yaa29%2F3xUOLbnmKTRaewPBs1%2FbezY8sbdGbU92l9zbua4pSkEse4JCDcmFK7bZgjT0ZTB7ZuWDoG9nGhypMPbL05c%2BR%2FGt1cR088vFaok%2FwDQVj9YpkWo6RVT9LneNYI6wSeWbvhH2u6H5CCVGHJn9KNqV1cf1SLM7EPq9zeUl9txLnqPe5iGJM%3D; utag_main=v_id:0169bded4df7004e2b43589d9c440008602b607e006f1$_sn:1$_ss:0$_st:1553671879597$ses_id:1553669639672%3Bexp-session$_pn:3%3Bexp-session$4split:2$4split2:2; criteo_write_test=ChUIBBINbXlHb29nbGVSdGJJZBgBIAE' -H 'Connection: keep-alive' --data 'utiming=speedindex:3134,b-stylesheets:843,b-fold:2189,b-pre-scripts:2297,b-post-scripts:2678' --compressed

curl 'https://www.booking.com/searchresults.en-us.html?label=gen173nr-1DCAEoggI46AdIM1gEaDuIAQGYATG4ARjIAQ_YAQPoAQH4AQKIAgGoAgS4Aq_c7OQFwAIB&sid=958b413f3d1ad36440d26e192779c81e&sb=1&src=index&src_elem=sb&error_url=https%3A%2F%2Fwww.booking.com%2Findex.html%3Flabel%3Dgen173nr-1DCAEoggI46AdIM1gEaDuIAQGYATG4ARjIAQ_YAQPoAQH4AQKIAgGoAgS4Aq_c7OQFwAIB%3Bsid%3D958b413f3d1ad36440d26e192779c81e%3Bsb_price_type%3Dtotal%26%3B&ss=Istanbul&is_ski_area=0&ssne=Istanbul&ssne_untouched=Istanbul&dest_id=-755070&dest_type=city&checkin_year=2019&checkin_month=3&checkin_monthday=29&checkout_year=2019&checkout_month=4&checkout_monthday=3&no_rooms=1&group_adults=2&group_children=0&b_h4u_keep_filters=&from_sf=1' 
-H 'Host: www.booking.com' 
-H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0' 
-H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' 
-H 'Accept-Language: en-US,en;q=0.5' 
-H 'Connection: keep-alive' 
-H 'Upgrade-Insecure-Requests: 1'
-H 'Referer: https://www.booking.com/' 
-H 'Cookie: bkng=11UmFuZG9tSVYkc2RlIyh9YXjA6rtNF48dyfPzTHjBgvuIJ2%2F%2B7G5RWU9qJGQNIQ34XjQRovTGwBzMpyUf2Y%2B9mMYUh6Ttd4NjTMEyhK9npQKG1qFMasgQS0UM91bNYxy1cNWwu09OyDEpqChVjodUptazaFtYi5YLd6B%2BW7FhDk5aGSRlslNta43jyOUEHoX7w3bBaFQrLUE%3D; _tq_id.TV-274536-1.3b4c=67de3ae2cf875ee1.1508627263.0.1553673783..; cors_js=1; cws=true; header_signin_prompt=1; BJS=-; lastSeen=1553673852968; _gcl_au=1.1.563916594.1553673230; utag_main=v_id:0169be242b8900398dfa78c8e0340004403b0009009dc$_sn:1$_ss:0$_st:1553675582829$ses_id:1553673235338%3Bexp-session$_pn:2%3Bexp-session$4split:2$4split2:1; zz_cook_tms_seg1=2; zz_cook_tms_ed=1; zz_cook_tms_seg3=5; cto_lwid=bd50f7d9-6d7d-430d-b8f3-0d7a77b59592; cto_idcpy=1e279f4c-a9be-4987-9126-80859f5c6334; has_preloaded=1' 
--compressed 


