* stages to form habbit
** Notticing
   - implentation intention
   - having specific plan for an action drastically
   increas the chance of actually following through your plan. I will
   do (the amount) at (time) in (place) format achieve the most result
   - having a plan will bypass the decision making process
   - give your goals a time an place
   - Failiure premortem(what challenges made the failure)
     - create IF Then plans to face challange
** Wanting
   your environment drives your desire, most often we want something
   because it is presented to us. You can change the environment to
   reflect the change in behavior you want to see by making the
   desired behavior easier and undesired behavior harder.
   - put the book you want to read on your bed to pick it up before
     bed time.
   - sticking to positive habbit consistently in a negative
     environment is impossible, if you are constantly fighting with
     environment you will fail.
   - you can avoid social media by actually not having your password
     accessible to you all the time.
   - put more steps between you and bad behavior and fewer steps
     between you and good behavior
** Doing
   - the most important thing in forming a habbit is just doing it. Do
     not over think it. It does't need to be perfect, it just needs to
     be.
   - any outcome you want to achive is a point in spectrum of
     repitition, the harder the goal, the more repetitions you need to
     achieve it.
   - Learning how to start matters. Make it as easy as possible to get
     started ( David allen 2 minutes rule of productivity).
   - Any habbit can start in under two minutes. Optimize for the
     starting line, making it as easy as possible to start.

** Liking
   - good habbit generally have a reward that is far away and a cost
     that is close, the key concept is to find a way to bring that
     reword forward in time.
   - best way to change long term behavior is with short term
     feedback.
   - The Seinfeld Strategy("Don't break the chain"): you will start by
     tracking your habbit, you will have false starts and hit and
     misses, once a chain of succession is formed your only goal is to
     not break the chain. Never miss twice.

* True Change Is not Behavior change Is Identity Change
  - You dont want to read a book, you wanna become a book Reader
  - you dont wanna write code, You wanna become programmer.
* Refrences
  James Clear
  [[https://www.youtube.com/watch?v=mNeXuCYiE0U][1% Better Every Day - James Clear at Craft]]
  https://www.youtube.com/watch?v=nRwDVD4Q26E

