* talk with nima
** me
*** days off
we have discussed one day off every week, however i have almost never taken that day off
i have tried to enforce 
*** vacation
you have asked me to cut my trip short by almost a week in new year, only to
attend a one hour, that was stupid.
*** attitude toward Afta
Afta has gone very good.
*** micro management attitude
i do not tolerate micro management. What my team is doing is my business. The
only report that you will see about the performance of my team is whether i'm
happy with their performance or not. There is not going to be any detail unless
we are going to provide a proper KPI and reward good performance. Even in that
case i do get direct feed back.
*** general attitude
i have requested an emergency meeting and so far you have not responded. If we
are going to define emergency this way i have absolutely no issue with it. Just
remember it goes both ways.
** My team
*** requests
**** Payment invoice
**** Health insurance
*** overtime
*** what up with double the time between 9:30 and 10:00
** Planning
*** 
