:PROPERTIES:
:ID:       a7273376-601d-4412-9114-9d16647b551b
:END:
#+title: life
* things i enjoy doing
** Photography
*** [[id:9424c217-d3e3-4c99-be2f-92ccf38ef1ce][computational photography]]
** Going out in the city
** Going out of the city
** Drawing
** Reading poem
*** [[id:05b5b53d-fdf7-4df6-af76-eb88868e0eaf][poets]]
** Reading books
*** [[https://sive.rs/book][Derek sivers]]
*** [[id:c874e322-7b34-4cc4-9a12-fb47918c94c0][books]]
** Watching movies/series
*** [[id:69115fd3-204b-488e-865f-28ad56403709][movies]]
*** [[id:bd32cb60-9a73-4cb0-8174-88a00d56f559][series]]
*** [[id:a727ff90-b9fe-43e4-ab6e-87e955226b7b][anime]]
** Listening to music
** Learning and Problem solving
** Cooking
** Dining out
** Having a high quality conversation
* thinks that are good if i enjoy them
** Exercise
*** How to make exercise fun ? 
* things i want to try
** Learn to shoot compound bow
** Learn to shoot gun
** writing
** Going out to galleries
** Going out to theater
** Scuba diving
** Get life-guard certificate
** Fly with para-glider
** Bungee jumping
** Zip-line
** Learn to play an instrument
** Learn to sing
** Learn to do electronics
** Start a social presence
** Mountain cycling
** Fly in a helicopter
** Rock climbing
** Do nude photo-shoot with a model
** Sexual experiments
*** threesome
* things that i want to achieve
** Physical fitness
*** Reach 90 KG
*** Get a nice 6 pack
*** Capable of doing a 180 with my legs
*** Can hang from an edge
** Learn to fight
*** Learn JUDO
*** Learn Boxing
*** Learn self defense
** Learn new languages
*** German
*** French
*** Russian
** Reach financial independence
** Have a foreign passport
* learning
** improve your note taking skills
** increase attention span
*** [[id:340377a0-aee8-4300-8094-a2d56498a191][Dopamine fasting]]
* imoprove my life
** do one year defining thing every year
** do a mini adventure every other month
** add a wining habit every quarter
* to view
** TODO [[https://www.youtube.com/watch?v=hAvskHhvDis][The One Habit That Is Changing My Life]]                        :watch:
** [[https://www.youtube.com/watch?v=RMB3NsQotvM][How to Force Your Brain To Be Motivated (when you don’t feel like it)]] :watch:
** [[https://www.youtube.com/watch?v=-wC_Oosh1Mw][Get Ahead of 99% of People by Thinking Backwards (Inversion Explained)]] :watch:
* change your life in 30 days
** cut the crap
*** choose 1 primary outcome for the next 30 days
*** choose 2 habit to drive it
*** say no to anything that  doesn't feed that one goal
if it's not a hell yes then it's a hell no
** when things are easy go hard
think about 2 time a year where most people take time of and then create
separation during that time, it's your time to improve and move ahead of the
rest of people
*** first 90 minutes of the day
the first 90 minutes of each day should be time you focus on your primary goal
*** skip the partying
*** one week day to double your habit
on the weekend focus on one thing that improves yourself and make you a better
fit for the situations that you are going to be in.
focus on learning, improving skills you need to master
** set daily none negotiable
*** 1-2 habit that feed your body
moving, stretching, eating your vitamins, exercise
*** 1-2 habit that feed your mind
reading at least 10 pages
meditation
mindfulness
*** 1-2 habit that move your business to move it forward
outreach
sales calls
create 3 stories daily about your business
improving your business relationships
** stop making excuses
staying in a warm bed feel grate but living the life you deserve feel fantastic
*** you can start your diet half way through a bag of chips
you do not need to wait for perfect time to start your journey, when ever you
start it it's the perfect time.
*** removing an excuse
**** give your excuse a name, say it out loud
when you name something you can interact with it more easily and discuss it
**** ask Does this serve me
challenge it, thing how this excuse is helpful in your life and how it's ruining your life
where does it come from
what happen when it's not in my life
put a spot lite on it
**** if you can't dissolve it ignore it
courage is not being fearless, courage is doing something despite being fearful 
** cut your time assassins
being successful is not about what you do, it's more about what you don't do.

scan your previous day for things that you wish you didn't do and create a
commitment for stopping yourself from doing so
*** notifications
remove all notifications from your phone

your focus and attention is worth way more to you than other people need to distract you
*** vices
alchohole
drugs
video game
*** energy vampire
look at the people in your life and remove the people that drain your energy

is an interaction easy,light,fun, did i learn something
if the answer is no then you should say no in the future
*** late night
nothing great happens after 9 pm

set an alarm for when you need to go to bed
create a going to bed routing instead of waking up routine
*** saying yes
say no to people who distract you from your goal
say no to distraction
say no to long conversation that don't go anywhere

NO is a full sentence and ends with period.
** stack the small wins
stack your wins that will build your belief that will eventually shape your identity
*** track your progress
what you measure will get managed
peter Druker

measure your steps per day
measure your weight
measure your revenue
measure your spending
measure what matters to you
**** measure your progress across multiple dimension
 - love
 - hobbies
 - money
 - spirituality
 - health
 - learning
 - growth
   for the two dimension with the lowest score chose one thing to be done for the next week to increase it's score
*** identify the win
when you celebrate the little the big will come
you have to identify the wins in your life, this way you will gear yourself towards the greater wins
*** share it with the world
when you share your wins you will become more consistent in your wins, because
you will fill the pressure to retain your wins
- Hurt
- Heal
- Help
** start today
imperfect action today beats planned action tomorrow that will never happen

true fulfillment comes from striving to be your 10.0 version every day and share yourself with the world
