:PROPERTIES:
:ID:       22ad1534-bb3b-47f8-aefd-c3ded9eed91c
:END:
#+title: my emotions
* feeling agitated and angry
** situation
*** Fatemeh basically friend-zoning me
 i keep finding my self cursing and being angry about the way she friend-zoned
 me. the funny thing is that i had no intention of actually getting it further
 at that moment. right now i feed hot in my head. i think the reason i feel this
 angry is because she put her self out of my reach.



 
 - maybe because she feels she is better than me ?

 i know one thing for sure right now, i don't think she has ever been in a
 proper relationship. because the way she said it's not gonna be like that.

 why do i feel bad about the situation?
  - honestly right now i would be out of option, Nothing is going on in my life
    at the moment. This is the deep issue that i need to address it as soon as possible.
  - the rejection i have seen so far kind of makes me doubt my value even though
    i know for a fact that i am quite valuable
  - 



  i really wanted to tell her that how high of yourself are you to assume such
  things. it's not like i'm in love with you. it's not like i'm proposing to
  you. it's not like i ask you out.



  what happend? our meeting was delayed due to bad planning and distance between
  the location that we entered in the park, after a while of walking around i
  shared my live location and waited for her to call me. we realized we are in
  the opposite sides of the park that are only joined via Tabiat bridge in the
  middle. reaching each other proved a bit problematic since she kept moving
  around. when we reach each other she was on the phone texting, after a few
  seconds he phone rang and she kept talking to a client for almost 15 or maybe
  20 minutes. we found a quiet place


  things we discussed
  - military service
  - how her family feels about me
  - my independence
  - i don't 
