:PROPERTIES:
:ID:       13E189E9-0A11-404D-9D8E-CBBAE58CA200
:END:
#+title: serotonin
serotonin is the chemical that caries message between nerve cells in the brain.
Serotonin plays a key role in mood sleep digestion nausea, wound healing , bone
health blood clotting and sexual desire. Serotonin levels that are too low or
too high can cause physical and psychological health problem.
** What is serotonin
Serotonin, also known as 5-hydroxytryptamine (5-HT), is a monoamine
neurotransmitter. It also acts as a hormone.

As a neurotransmitter, serotonin carries messages between nerve cells in your
brain (your central nervous system) and throughout your body (your peripheral
nervous system). These chemical messages tell your body how to work.

Serotonin plays several roles in your body, including influencing learning,
memory, happiness as well as regulating body temperature, sleep, sexual behavior
and hunger. Lack of enough serotonin is thought to play a role in depression,
anxiety, mania and other health conditions.

Most of the serotonin found in your body is in your gut (intestines). About 90%
of serotonin is found in the cells lining your gastrointestinal tract. It’s
released into your blood circulation and absorbed by platelets. Only about 10%
is produced in your brain.

Serotonin is made from the essential amino acid tryptophan. An essential amino
acid means it can’t be made by your body. It has to be obtained from the foods
you eat.
** What does serotonin do in my body?
Serotonin plays a role in many of your body’s functions:

*** Mood
Serotonin in your brain regulates your mood. It’s often called your body’s
natural “feel good” chemical. When serotonin is at normal levels, you feel more
focused, emotionally stable, happier and calmer. Low levels of serotonin are
associated with depression. Many medications used to treat anxiety, depression
and other mood disorders often target ways to increase the level of serotonin in
your brain.
*** Digestion
Most of your body’s serotonin is in your GI tract where it helps control your
bowel function and plays a role in protecting your gut. Your gut can increase
serotonin release to speed digestion to rid your body of irritating foods or
toxic products. Serotonin also plays a part in reducing your appetite while
eating.
*** Nausea
Nausea is triggered when serotonin is released into your gut faster than it can
be digested. The chemical message is received by your brain, which you perceive
as nausea. Many drugs used to reduce feelings of nausea and vomiting target
specific serotonin receptors in your brain.
*** Sleep
Serotonin, together with another neurotransmitter dopamine, plays a role in the
quality of your sleep (how well and how long you sleep). Your brain also needs
serotonin to make melatonin, a hormone that regulates your sleep-wake cycle.
*** Wound healing
Serotonin is released by platelets in your blood to help heal wounds. It also
causes the tiniest blood vessels, arterioles, to narrow, which slows blood flow
and helps clots to form. This is an important process in wound healing.
*** Bone health
Serotonin levels may play a role in the density of your bones. High levels of
serotonin in your gut may play a role in making bones weak, which can lead to
bone breaks (fractures) and osteoporosis.
*** Sexual health
Serotonin also plays a role — together with the neurotransmitter dopamine — in
your desire for sex.
** What problems are associated with low serotonin levels?
Low levels of serotonin may be associated with many health conditions including:
Depression and other mood problems.
Anxiety.
Sleep problems.
Digestive problems.
Suicidal behavior.
Obsessive-compulsive disorder.
Post-traumatic stress disorder.
Panic disorders.
Schizophrenia.
Phobias.
Scientists still have a lot to learn about the role of serotonin in the body and in disease.

** What can cause low serotonin levels?

A low serotonin level usually has more than one cause. Technically, serotonin
levels are low because:

Your body isn’t producing enough serotonin. Your body isn’t effectively using
serotonin. This can happen if you don’t have enough serotonin receptors or the
receptors aren’t working as they should. What can I do to increase serotonin
levels?

** Ways to increase serotonin levels include:

Eating more tryptophan-containing foods.
Getting more sunlight.
Taking certain supplements.
Getting more exercise and lowering your stress level.
Foods to increase serotonin levels

Many foods naturally contain tryptophan, the amino acid from which serotonin is
made. You can try increasing your serotonin level by eating
tryptophan-containing foods, such as:

Salmon.
Eggs.
Cheese.
Turkey.
Tofu.
Pineapples.
Nuts, oats and seeds.
Eating foods high in tryptophan will not necessarily boost serotonin levels on its own. It’s a complex process. Your body needs carbohydrates to release insulin, which is needed to absorb amino acids. Then even if tryptophan does get into your blood it has to compete with other amino acids to get absorbed into your brain. Scientists are still studying how eating tryptophan-containing foods possibly boosts serotonin levels.

Sunlight

Not getting enough exposure to sunlight can lead to the mood disorder seasonal
affective disorder in some people. Try to get 10 to 15 minutes of sunlight each
day to boost not only serotonin levels but vitamin D levels too. If you live in
an area where you can’t get natural sunlight, consider using light therapy to
get that needed daily sunlight.

Supplements

Several dietary and herbal supplements also increase serotonin levels. These include:

Dietary supplement: Tryptophan, probiotics and SAMe.
Herbal supplements: These can include ginseng, St. John’s wort, Syrian rue and nutmeg.
Exercise

Regular exercise is known to increase serotonin levels. Thirty minutes of
aerobic exercise five times a week plus two strength-training sessions per week
can improve mood disorders and heart health.

** What medications increase serotonin levels?

Serotonin or serotonin receptors are common targets of the pharmaceutical
industry since many health conditions are affected by serotonin. Some of the
more common medications that increase serotonin levels include the following.

Several different classes of antidepressants block the reabsorption and
recycling of serotonin, allowing more to remain in the brain. Medications that
work this way are selective serotonin reuptake inhibitors (for example,
paroxetine [Paxil®]), serotonin-norepinephrine reuptake inhibitors (for example,
venlafaxine [Effexor®]) and tricyclic antidepressants (for example,
amitriptyline [Elavil®]). Another type of antidepressant, monoamine oxidase
inhibitors (for example, phenelzine [Nardil®]) blocks an enzyme that breaks down
serotonin.

Many other medications, taken for many medical conditions, also increase
serotonin. Some of these drugs include the triptan family of headache drugs,
opioid pain relievers, dextromethorphan-containing cough suppressants and
anti-nausea drugs.

** What problems are associated with high serotonin levels?

Serotonin syndrome is a condition that happens when serotonin levels are
increased too much. It usually happens if you increase the dose of a medication
known to increase serotonin levels or take another drug known to increase
serotonin.

Mild symptoms include shivering, heavy sweating, confusion, restlessness, high
blood pressure, muscle twitches and diarrhea. Severe symptoms include high
fever, seizures, fainting and abnormal heartbeat.

Serotonin syndrome can be fatal if it’s severe and not caught early and treated
quickly.


