:PROPERTIES:
:ID:       305C1F31-5238-4E38-BE9E-54512B29D322
:END:
#+title: asset-flo
* information
** server
5.189.160.91
user: root
password:j6jK8iVTZJhSN99




[[https://docs.google.com/document/d/1IzLl7LwCZDft6kiuFNkVYmQgB0VRxt10wWJ1YSWA1SM/edit?tab=t.0][original proposal document]]
** users
admin@example.com
Bro38860
** ad account
319438279876094
** ad id with data
120212383814830774
** previous token
curl -G \
  -d "fields=name,username,link,about,followers_count" \
  -d "access_token=EAAQDU9ylEQ0BQLbnx4Hgd6Rm7G7X4PsPIpS5lXqpw8c4GZBTe5MJpId6bGQmjSJV4BU9lTkELxMw8M4OmmbZAoZCMUlAyNVL17KgUZCWtLKWdlVNos7NGAZBZAF7XBzVF40VzOPeyx1ZAuaMlx7IerBG56oahaZAiSOfPUGSrmMby3ij2sR8K4VSaJeOZASyZBMZBrSDW2x52fG1I0eL2Taa4PvjPhQcavZAEXzwD93uTfLaS4Vrp5c3IdNnZAYeNibpC9t6AGXviR1n1VTEn2CEDhwPcvjcniN6gA9DsNdHv" \
  "https://graph.facebook.com/v19.0/100230198932502"
* tasks
** reading and learning documents
:LOGBOOK:
CLOCK: [2025-08-11 Mon 10:59]--[2025-08-11 Mon 11:57] =>  0:58
CLOCK: [2025-08-08 Fri 12:10]--[2025-08-08 Fri 14:00] =>  1:50
CLOCK: [2025-08-08 Fri 10:12]--[2025-08-08 Fri 11:27] =>  1:15
CLOCK: [2025-08-07 Thu 22:10]--[2025-08-07 Thu 22:45] =>  0:35
CLOCK: [2025-08-07 Thu 11:00]--[2025-08-07 Thu 11:45] =>  0:45
:END:
*** meta
**** figure out how we are going to connect to Meta
**** figure out how we are going to list assets connected to a meta account
**** figure out how to collect performance of a asset in meta
*** figure out AI analysis pipline
https://g.co/gemini/share/056227ca6797
** Reading the Documents and preparing access
** setting up the project
:LOGBOOK:
CLOCK: [2025-11-14 Fri 12:02]--[2025-11-14 Fri 16:02] =>  4:00
CLOCK: [2025-11-13 Thu 18:28]--[2025-11-13 Thu 21:47] =>  3:19
CLOCK: [2025-11-10 Mon 18:27]--[2025-11-10 Mon 20:28] =>  2:01
CLOCK: [2025-11-08 Sat 15:28]--[2025-11-08 Sat 18:39] =>  3:11
CLOCK: [2025-10-31 Fri 10:45]--[2025-10-31 Fri 11:43] =>  0:58
CLOCK: [2025-10-31 Fri 09:15]--[2025-10-31 Fri 09:45] =>  0:30
CLOCK: [2025-10-31 Fri 06:40]--[2025-10-31 Fri 08:38] =>  1:58
:END:
** setting up initial demo
:LOGBOOK:
CLOCK: [2025-11-15 Sat 18:43]--[2025-11-15 Sat 22:05] =>  3:22
:END:
*** DONE get access to access token                                   :admin:
CLOSED: [2025-11-15 Sat 19:35]
:LOGBOOK:
- State "DONE"       from "DOINGNOW"   [2025-11-15 Sat 19:35]
- State "DOINGNOW"   from "BLOCKED"    [2025-11-15 Sat 19:35]
- State "BLOCKED"    from "DELEGATED"  [2025-11-15 Sat 19:34]
- State "DELEGATED"  from "DONE"       [2025-10-31 Fri 09:03]
- State "DONE"       from "TODO"       [2025-10-31 Fri 09:03]
- State "TODO"       from              [2025-10-31 Fri 09:01]
:END:
** get proper access to facebook
*** BLOCKED set up facebook account                                   :admin:
:LOGBOOK:
- State "BLOCKED"    from "DELEGATED"  [2025-11-15 Sat 19:35]
- State "DELEGATED"  from              [2025-10-31 Fri 09:02]
:END:
*** BLOCKED set up associated gmail account                           :admin:
:LOGBOOK:
- State "BLOCKED"    from "DELEGATED"  [2025-11-15 Sat 19:35]
- State "DELEGATED"  from              [2025-10-31 Fri 09:02]
:END:
*** ask admin to add FACEBOOK_REDIRECT_URI to whitelist urls
FACEBOOK_REDIRECT_URI=http://localhost:3000/auth/meta/callback
** setting up server
:LOGBOOK:
CLOCK: [2025-10-31 Fri 08:45]--[2025-10-31 Fri 10:01] =>  1:16
CLOCK: [2025-10-31 Fri 08:38]--[2025-10-31 Fri 08:58] =>  0:20
:END:
** working on integrating with ads
:LOGBOOK:
CLOCK: [2025-12-12 Fri 11:30]
CLOCK: [2025-12-11 Thu 05:57]--[2025-12-11 Thu 09:41] =>  3:44
CLOCK: [2025-12-09 Tue 16:38]--[2025-12-09 Tue 19:54] =>  3:16
CLOCK: [2025-12-03 Wed 14:33]--[2025-12-03 Wed 16:40] =>  2:07
CLOCK: [2025-12-01 Mon 16:05]--[2025-12-01 Mon 20:00] =>  3:55
CLOCK: [2025-11-28 Fri 12:45]--[2025-11-28 Fri 15:27] =>  2:42
CLOCK: [2025-11-27 Thu 21:17]--[2025-11-27 Thu 22:25] =>  1:08
CLOCK: [2025-11-27 Thu 14:01]--[2025-11-27 Thu 17:12] =>  3:11
CLOCK: [2025-11-25 Tue 16:00]--[2025-11-25 Tue 17:59] =>  1:59
CLOCK: [2025-11-24 Mon 08:00]--[2025-11-24 Mon 09:44] =>  1:44
:END:
** meeting 
:LOGBOOK:
CLOCK: [2025-10-31 Fri 11:30]--[2025-10-31 Fri 12:09] =>  0:39
:END:
* data

{
  "success": true,
  "count": 25,
  "data": [
    {
      "id": "120236486078960774",
      "name": "Johnson PP",
      "status": "PAUSED",
      "adset_id": "120207698522320774",
      "campaign_id": "120207698522210774",
      "creative": {
        "id": "691250047108064"
      },
      "created_time": "2025-11-25T06:41:45+0000",
      "updated_time": "2025-11-27T04:15:31+0000",
      "preview_shareable_link": "https://fb.me/27U7zKrGDINHy8T",
      "source_ad": {
        "id": "120233084654720774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1150818460535812"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1150818460535812"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1150818460535812"
          ]
        }
      ]
    },
    {
      "id": "120236486208220774",
      "name": "Thomas PP",
      "status": "ACTIVE",
      "adset_id": "120207698522320774",
      "campaign_id": "120207698522210774",
      "creative": {
        "id": "848590547755063"
      },
      "created_time": "2025-11-25T06:44:53+0000",
      "updated_time": "2025-11-26T15:05:27+0000",
      "preview_shareable_link": "https://fb.me/2kXUNzuYIDQJTPD",
      "source_ad": {
        "id": "120236486078960774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1150817097202615"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1150817097202615"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1150817097202615"
          ]
        }
      ]
    },
    {
      "id": "120236485882700774",
      "name": "Bidwell PP",
      "status": "ACTIVE",
      "adset_id": "120207698522320774",
      "campaign_id": "120207698522210774",
      "creative": {
        "id": "2351409148610971"
      },
      "created_time": "2025-11-25T06:36:39+0000",
      "updated_time": "2025-11-25T12:57:50+0000",
      "preview_shareable_link": "https://fb.me/24ue2MrzyFzZBKs",
      "source_ad": {
        "id": "120212383814830774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1151015203849471"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1151015203849471"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1151015203849471"
          ],
          "post.wall": [
            "100230198932502"
          ]
        }
      ]
    },
    {
      "id": "120212383814830774",
      "name": "Wardrobe",
      "status": "PAUSED",
      "adset_id": "120207698522320774",
      "campaign_id": "120207698522210774",
      "creative": {
        "id": "120212424946050774"
      },
      "created_time": "2024-10-21T16:41:31+0000",
      "updated_time": "2025-11-25T06:30:48+0000",
      "preview_shareable_link": "https://fb.me/1XXEFFmy2HYm0uT",
      "source_ad": {
        "id": "120212383778640774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "7661298917270570",
            "7836567503067619",
            "8004597956237459",
            "8139367502761799",
            "8246341365410283"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "858447186439609"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "858447186439609"
          ],
          "post.wall": [
            "100230198932502"
          ]
        }
      ]
    },
    {
      "id": "120217070202570774",
      "name": "Pulp Fiction",
      "status": "PAUSED",
      "adset_id": "120207698522320774",
      "campaign_id": "120207698522210774",
      "creative": {
        "id": "1424165292326334"
      },
      "created_time": "2025-02-27T09:47:48+0000",
      "updated_time": "2025-11-24T03:30:52+0000",
      "preview_shareable_link": "https://fb.me/1XHnvVSS0RGOcG7",
      "source_ad": {
        "id": "120214997211110774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "7661298917270570",
            "7836567503067619",
            "8004597956237459",
            "8139367502761799",
            "8246341365410283"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "944117591205901"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "944117591205901"
          ],
          "post.wall": [
            "100230198932502"
          ]
        }
      ]
    },
    {
      "id": "120233084654720774",
      "name": "Boys On Tour.",
      "status": "PAUSED",
      "adset_id": "120207698522320774",
      "campaign_id": "120207698522210774",
      "creative": {
        "id": "816376214404173"
      },
      "created_time": "2025-09-30T09:46:51+0000",
      "updated_time": "2025-11-22T05:08:56+0000",
      "preview_shareable_link": "https://fb.me/1Y6H1VrNZMEL79r",
      "source_ad": {
        "id": "120233084509250774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1104677988483193"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        }
      ]
    },
    {
      "id": "120235770661120774",
      "name": "Pulp Fiction – Copy",
      "status": "ACTIVE",
      "adset_id": "120235770661340774",
      "campaign_id": "120235770661430774",
      "creative": {
        "id": "4300123570271406"
      },
      "created_time": "2025-11-13T17:24:42+0000",
      "updated_time": "2025-11-13T17:29:06+0000",
      "preview_shareable_link": "https://fb.me/1P4r5tMNX8FdB97",
      "source_ad": {
        "id": "120235770620330774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1142200008064324"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200008064324"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200008064324"
          ]
        }
      ]
    },
    {
      "id": "120235770661240774",
      "name": "Pulp Fiction – Copy",
      "status": "ACTIVE",
      "adset_id": "120235770661370774",
      "campaign_id": "120235770661430774",
      "creative": {
        "id": "1658232725561100"
      },
      "created_time": "2025-11-13T17:24:18+0000",
      "updated_time": "2025-11-13T17:28:38+0000",
      "preview_shareable_link": "https://fb.me/1N50qT1DeubAXbT",
      "source_ad": {
        "id": "120235770620140774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200004730991"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200004730991"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1142200004730991"
          ],
          "post.wall": [
            "100230198932502"
          ]
        }
      ]
    },
    {
      "id": "120235770661470774",
      "name": "Pulp Fiction – Copy",
      "status": "ACTIVE",
      "adset_id": "120235770661320774",
      "campaign_id": "120235770661430774",
      "creative": {
        "id": "25244520278497916"
      },
      "created_time": "2025-11-13T17:24:42+0000",
      "updated_time": "2025-11-13T17:28:27+0000",
      "preview_shareable_link": "https://fb.me/1RkA3YM8JOTNgw1",
      "source_ad": {
        "id": "120235770620090774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1142199984730993"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142199984730993"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142199984730993"
          ]
        }
      ]
    },
    {
      "id": "120235770661590774",
      "name": "Pulp Fiction – Copy",
      "status": "ACTIVE",
      "adset_id": "120235770661350774",
      "campaign_id": "120235770661430774",
      "creative": {
        "id": "816969834461213"
      },
      "created_time": "2025-11-13T17:24:18+0000",
      "updated_time": "2025-11-13T17:27:58+0000",
      "preview_shareable_link": "https://fb.me/2gY127eJeZM9Jf4",
      "source_ad": {
        "id": "120235770620110774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1142200018064323"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200018064323"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200018064323"
          ]
        }
      ]
    },
    {
      "id": "120235770620110774",
      "name": "Pulp Fiction – Copy",
      "status": "ACTIVE",
      "adset_id": "120235210749810774",
      "campaign_id": "120235210749510774",
      "creative": {
        "id": "816969834461213"
      },
      "created_time": "2025-11-13T17:23:10+0000",
      "updated_time": "2025-11-13T17:27:34+0000",
      "preview_shareable_link": "https://fb.me/22sUQHnq4l3z6Ql",
      "source_ad": {
        "id": "120217070202570774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1142200018064323"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200018064323"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200018064323"
          ]
        }
      ]
    },
    {
      "id": "120235770661400774",
      "name": "Pulp Fiction – Copy",
      "status": "ACTIVE",
      "adset_id": "120235770661330774",
      "campaign_id": "120235770661430774",
      "creative": {
        "id": "860430489782938"
      },
      "created_time": "2025-11-13T17:24:59+0000",
      "updated_time": "2025-11-13T17:26:36+0000",
      "preview_shareable_link": "https://fb.me/1YrFYW1EMph6FLO",
      "source_ad": {
        "id": "120235770620240774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1142200028064322"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200028064322"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200028064322"
          ]
        }
      ]
    },
    {
      "id": "120235770661310774",
      "name": "Boys On Tour. – Copy",
      "status": "ACTIVE",
      "adset_id": "120235770661360774",
      "campaign_id": "120235770661430774",
      "creative": {
        "id": "816376214404173"
      },
      "created_time": "2025-11-13T17:24:56+0000",
      "updated_time": "2025-11-13T17:26:36+0000",
      "preview_shareable_link": "https://fb.me/1XyVrSuZxku6byF",
      "source_ad": {
        "id": "120235770620150774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1104677988483193"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        }
      ]
    },
    {
      "id": "120235770661290774",
      "name": "Pulp Fiction – Copy",
      "status": "ACTIVE",
      "adset_id": "120235770661360774",
      "campaign_id": "120235770661430774",
      "creative": {
        "id": "2557085924675029"
      },
      "created_time": "2025-11-13T17:24:59+0000",
      "updated_time": "2025-11-13T17:26:27+0000",
      "preview_shareable_link": "https://fb.me/3015GvnHXnbotH7",
      "source_ad": {
        "id": "120235770620190774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142199991397659"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1142199991397659"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142199991397659"
          ]
        }
      ]
    },
    {
      "id": "120235770661580774",
      "name": "Boys On Tour. – Copy",
      "status": "ACTIVE",
      "adset_id": "120235770661330774",
      "campaign_id": "120235770661430774",
      "creative": {
        "id": "816376214404173"
      },
      "created_time": "2025-11-13T17:24:56+0000",
      "updated_time": "2025-11-13T17:26:16+0000",
      "preview_shareable_link": "https://fb.me/297jRgsMN2j1L3E",
      "source_ad": {
        "id": "120235770620250774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1104677988483193"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        }
      ]
    },
    {
      "id": "120235770661500774",
      "name": "Boys On Tour. – Copy",
      "status": "ACTIVE",
      "adset_id": "120235770661320774",
      "campaign_id": "120235770661430774",
      "creative": {
        "id": "816376214404173"
      },
      "created_time": "2025-11-13T17:24:36+0000",
      "updated_time": "2025-11-13T17:26:04+0000",
      "preview_shareable_link": "https://fb.me/AfUfbZHIocOgXAt",
      "source_ad": {
        "id": "120235770620080774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1104677988483193"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        }
      ]
    },
    {
      "id": "120235770661180774",
      "name": "Boys On Tour. – Copy",
      "status": "ACTIVE",
      "adset_id": "120235770661340774",
      "campaign_id": "120235770661430774",
      "creative": {
        "id": "816376214404173"
      },
      "created_time": "2025-11-13T17:24:36+0000",
      "updated_time": "2025-11-13T17:26:01+0000",
      "preview_shareable_link": "https://fb.me/29y0JTVA4lJf6ay",
      "source_ad": {
        "id": "120235770620340774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1104677988483193"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        }
      ]
    },
    {
      "id": "120235770661620774",
      "name": "Boys On Tour. – Copy",
      "status": "ACTIVE",
      "adset_id": "120235770661350774",
      "campaign_id": "120235770661430774",
      "creative": {
        "id": "816376214404173"
      },
      "created_time": "2025-11-13T17:24:27+0000",
      "updated_time": "2025-11-13T17:25:52+0000",
      "preview_shareable_link": "https://fb.me/2muHWfxlmOjjxb4",
      "source_ad": {
        "id": "120235770620120774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1104677988483193"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        }
      ]
    },
    {
      "id": "120235770661220774",
      "name": "Boys On Tour. – Copy",
      "status": "ACTIVE",
      "adset_id": "120235770661370774",
      "campaign_id": "120235770661430774",
      "creative": {
        "id": "816376214404173"
      },
      "created_time": "2025-11-13T17:24:21+0000",
      "updated_time": "2025-11-13T17:25:51+0000",
      "preview_shareable_link": "https://fb.me/2gG3C4YPvcBNL7H",
      "source_ad": {
        "id": "120235770620130774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1104677988483193"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        }
      ]
    },
    {
      "id": "120235770620190774",
      "name": "Pulp Fiction – Copy",
      "status": "ACTIVE",
      "adset_id": "120235213777890774",
      "campaign_id": "120235210749510774",
      "creative": {
        "id": "2557085924675029"
      },
      "created_time": "2025-11-13T17:23:10+0000",
      "updated_time": "2025-11-13T17:25:23+0000",
      "preview_shareable_link": "https://fb.me/2drmMsb3lUBDQay",
      "source_ad": {
        "id": "120217070202570774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142199991397659"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1142199991397659"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142199991397659"
          ]
        }
      ]
    },
    {
      "id": "120235770620240774",
      "name": "Pulp Fiction – Copy",
      "status": "ACTIVE",
      "adset_id": "120235213777860774",
      "campaign_id": "120235210749510774",
      "creative": {
        "id": "860430489782938"
      },
      "created_time": "2025-11-13T17:23:10+0000",
      "updated_time": "2025-11-13T17:25:13+0000",
      "preview_shareable_link": "https://fb.me/1XWtvJOl6TFQMr1",
      "source_ad": {
        "id": "120217070202570774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1142200028064322"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200028064322"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200028064322"
          ]
        }
      ]
    },
    {
      "id": "120235770620090774",
      "name": "Pulp Fiction – Copy",
      "status": "ACTIVE",
      "adset_id": "120235213777880774",
      "campaign_id": "120235210749510774",
      "creative": {
        "id": "25244520278497916"
      },
      "created_time": "2025-11-13T17:23:10+0000",
      "updated_time": "2025-11-13T17:24:59+0000",
      "preview_shareable_link": "https://fb.me/1QaQWm1cW8jWfYu",
      "source_ad": {
        "id": "120217070202570774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1142199984730993"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142199984730993"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142199984730993"
          ]
        }
      ]
    },
    {
      "id": "120235770620330774",
      "name": "Pulp Fiction – Copy",
      "status": "ACTIVE",
      "adset_id": "120235213777870774",
      "campaign_id": "120235210749510774",
      "creative": {
        "id": "4300123570271406"
      },
      "created_time": "2025-11-13T17:23:10+0000",
      "updated_time": "2025-11-13T17:24:58+0000",
      "preview_shareable_link": "https://fb.me/1RUb8Qz0aC4IImm",
      "source_ad": {
        "id": "120217070202570774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1142200008064324"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200008064324"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200008064324"
          ]
        }
      ]
    },
    {
      "id": "120235770620140774",
      "name": "Pulp Fiction – Copy",
      "status": "ACTIVE",
      "adset_id": "120235213777850774",
      "campaign_id": "120235210749510774",
      "creative": {
        "id": "1658232725561100"
      },
      "created_time": "2025-11-13T17:23:10+0000",
      "updated_time": "2025-11-13T17:24:57+0000",
      "preview_shareable_link": "https://fb.me/25QmQj5nSWkJFUA",
      "source_ad": {
        "id": "120217070202570774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200004730991"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1142200004730991"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1142200004730991"
          ],
          "post.wall": [
            "100230198932502"
          ]
        }
      ]
    },
    {
      "id": "120235770620150774",
      "name": "Boys On Tour. – Copy",
      "status": "ACTIVE",
      "adset_id": "120235213777890774",
      "campaign_id": "120235210749510774",
      "creative": {
        "id": "816376214404173"
      },
      "created_time": "2025-11-13T17:23:10+0000",
      "updated_time": "2025-11-13T17:24:47+0000",
      "preview_shareable_link": "https://fb.me/266UXDcYGbY93Aa",
      "source_ad": {
        "id": "120233084654720774"
      },
      "tracking_specs": [
        {
          "action.type": [
            "commerce_event"
          ],
          "page": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "offsite_conversion"
          ],
          "fb_pixel": [
            "4503792916343521"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ],
          "conversion_id": [
            "24683046084634609"
          ]
        },
        {
          "action.type": [
            "onsite_conversion"
          ]
        },
        {
          "action.type": [
            "link_click"
          ],
          "post": [
            "1104677988483193"
          ],
          "post.wall": [
            "100230198932502"
          ]
        },
        {
          "action.type": [
            "post_engagement"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        },
        {
          "action.type": [
            "post_interaction_gross"
          ],
          "page": [
            "100230198932502"
          ],
          "post": [
            "1104677988483193"
          ]
        }
      ]
    }
  ]
}
* information and apis
** get token permissions

curl https://graph.facebook.com/v24.0/me/permissions?access_token=EAAQDU9ylEQ0BQGu9hIKETR82Q5a7ZAsA3qalQFVY6HRVyilAlwOY2rqTzZCYM5ZBOLEWkNtHziwPC2f3W5w0IlauaqxqIn2KXgLjUhulZC58WpZAGRjgitsXY8YiiufTOUKLKGj3ZB0c8ZBWtWUZCu4F8Sjecko2nLjZBc2Cxy6dJewPEbhfWeKo2d7nrUIQTfmB4teQ5gI3Dj3ZAo0LUcHuvZBjNL083OTR2fZAIPrPtZB56GZAZAgHP6DohdRnFCZCWoBprQagd5UKnMUg5pzOjZBFzkf93Cb8TFxRRO4L4YPhN|jq
** getting the video
curl -G \
  "https://graph.facebook.com/v24.0/2407670316347233" \
  -d "access_token=EAAQDU9ylEQ0BQGu9hIKETR82Q5a7ZAsA3qalQFVY6HRVyilAlwOY2rqTzZCYM5ZBOLEWkNtHziwPC2f3W5w0IlauaqxqIn2KXgLjUhulZC58WpZAGRjgitsXY8YiiufTOUKLKGj3ZB0c8ZBWtWUZCu4F8Sjecko2nLjZBc2Cxy6dJewPEbhfWeKo2d7nrUIQTfmB4teQ5gI3Dj3ZAo0LUcHuvZBjNL083OTR2fZAIPrPtZB56GZAZAgHP6DohdRnFCZCWoBprQagd5UKnMUg5pzOjZBFzkf93Cb8TFxRRO4L4YPhN" \
  -d "fields=source,permalink_url,description,length"
** getting a list of all add campaings and adcreatives
curl -G \
  "https://graph.facebook.com/v19.0/act_YOUR_AD_ACCOUNT_ID/campaigns" \
  -d "access_token=EAAQDU9ylEQ0BQGu9hIKETR82Q5a7ZAsA3qalQFVY6HRVyilAlwOY2rqTzZCYM5ZBOLEWkNtHziwPC2f3W5w0IlauaqxqIn2KXgLjUhulZC58WpZAGRjgitsXY8YiiufTOUKLKGj3ZB0c8ZBWtWUZCu4F8Sjecko2nLjZBc2Cxy6dJewPEbhfWeKo2d7nrUIQTfmB4teQ5gI3Dj3ZAo0LUcHuvZBjNL083OTR2fZAIPrPtZB56GZAZAgHP6DohdRnFCZCWoBprQagd5UKnMUg5pzOjZBFzkf93Cb8TFxRRO4L4YPhN" \
  -d "limit=50" \
  -d "fields=name,id,ads{name,adlabels,adcreatives{title,body,image_url,thumbnail_url,object_story_spec,asset_feed_spec}}"
